nelmio_api_doc:
    documentation:
        info:
            title: 'SimpleTravel API'
            description: 'ğŸŒ Dokumentacja backendu Symfony z endpointami aplikacji do zarzÄ…dzania podrÃ³Å¼Ä…'
            version: '1.1'
        tags:
            - name: 'ğŸ”’ Auth'
              description: 'Rejestracja, logowanie, uÅ¼ytkownik zalogowany, wylogowywanie.'
            - name: 'âœˆï¸ Trip'
              description: 'Tworzenie, edycja, pobieranie i usuwanie wycieczek.'
            - name: 'ğŸ› ï¸ In progress'
              description: 'Zaplanowane endpointy, ktÃ³re nie majÄ… jeszcze zastosowania w aplikacji.'

    areas:
        default:
            path_patterns: [ '^/api' ]
